[build]
publish = "."

[[redirects]]
from = "/reset-password"
to = "/reset-password.html"
status = 200

[[redirects]]
from = "/reset-password/"
to = "/reset-password.html"
status = 200

[[redirects]]
from = "/forgot-password"
to = "/forgot-password.html"
status = 200

[[redirects]]
from = "/forgot-password/"
to = "/forgot-password.html"
status = 200