[build]
publish = "."

[[redirects]]
from = "/api/*"
to = "https://awa-pp4u.onrender.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/reset-password"
to = "/reset-password.html"
status = 200

[[redirects]]
from = "/reset-password/"
to = "/reset-password.html"
status = 200

[[redirects]]
from = "/forgot-password"
to = "/forgot-password.html"
status = 200

[[redirects]]
from = "/forgot-password/"
to = "/forgot-password.html"
status = 200
